import "./Header/Header.js"
import "./CardBalance/CardBalance.js"
import "./CardNews/CardNews.js"
import "./NotificationsModal/NotificationsModal.js"
import "./NavBar/NavBar.js"
import "./FarmingModal/FarmingModal.js"
import "./CardInvite/CardInvite.js"